// <auto-generated />
using System;
using App_Bancaria_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App_Bancaria_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420041405_RemoveTokenFromUsuario")]
    partial class RemoveTokenFromUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App_Bancaria_Backend.Models.Aporte", b =>
                {
                    b.Property<int>("IdAporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAporte"));

                    b.Property<string>("CodAporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int>("IdTransaccion")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdAporte");

                    b.HasIndex("IdGrupo");

                    b.HasIndex("IdTransaccion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Aporte");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.Cuenta", b =>
                {
                    b.Property<int>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuenta"));

                    b.Property<string>("CodCuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodQR")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCuenta");

                    b.HasIndex("CodCuenta")
                        .IsUnique();

                    b.HasIndex("CodQR")
                        .IsUnique();

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Cuenta");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.GrupoAdministrador", b =>
                {
                    b.Property<int>("IdGrupoAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupoAdmin"));

                    b.Property<string>("CodGrupoAdmin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdGrupoAdmin");

                    b.HasIndex("IdGrupo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("GrupoAdministrador");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.GrupoAhorro", b =>
                {
                    b.Property<int>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupo"));

                    b.Property<string>("CodGrupo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoObjetivo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGrupo");

                    b.ToTable("GrupoAhorro");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.GrupoMiembro", b =>
                {
                    b.Property<int>("IdGrupoMiembro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupoMiembro"));

                    b.Property<string>("CodGrupoMiembro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaUnion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdGrupoMiembro");

                    b.HasIndex("IdGrupo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("GrupoMiembro");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.Retiro", b =>
                {
                    b.Property<int>("IdRetiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRetiro"));

                    b.Property<string>("CodRetiro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioSolicitante")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdRetiro");

                    b.HasIndex("IdGrupo");

                    b.HasIndex("IdUsuarioSolicitante");

                    b.ToTable("Retiro");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.RetiroAprobacion", b =>
                {
                    b.Property<int>("IdAprobacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAprobacion"));

                    b.Property<bool>("Aprobado")
                        .HasColumnType("bit");

                    b.Property<string>("CodAprobacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdRetiro")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdAprobacion");

                    b.HasIndex("IdRetiro");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RetiroAprobacion");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.TipoTransaccion", b =>
                {
                    b.Property<int>("IdTipoTransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoTransaccion"));

                    b.Property<string>("CodTipoTransaccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoTransaccion");

                    b.ToTable("TipoTransaccion");

                    b.HasData(
                        new
                        {
                            IdTipoTransaccion = 1,
                            CodTipoTransaccion = "T001",
                            Nombre = "Transferencia"
                        },
                        new
                        {
                            IdTipoTransaccion = 2,
                            CodTipoTransaccion = "T002",
                            Nombre = "Aporte"
                        },
                        new
                        {
                            IdTipoTransaccion = 3,
                            CodTipoTransaccion = "T003",
                            Nombre = "Retiro"
                        },
                        new
                        {
                            IdTipoTransaccion = 4,
                            CodTipoTransaccion = "T004",
                            Nombre = "Recarga"
                        });
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.Transaccion", b =>
                {
                    b.Property<int>("IdTransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransaccion"));

                    b.Property<string>("CodTransaccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("IdCuentaDestino")
                        .HasColumnType("int");

                    b.Property<int>("IdCuentaOrigen")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoTransaccion")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdTransaccion");

                    b.HasIndex("IdCuentaDestino");

                    b.HasIndex("IdCuentaOrigen");

                    b.HasIndex("IdTipoTransaccion");

                    b.ToTable("Transaccion");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ApeMate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApePat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("FlgEli")
                        .HasColumnType("bit");

                    b.Property<bool>("FlgEstado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("CodUsuario")
                        .IsUnique();

                    b.HasIndex("NroTelefono")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.Aporte", b =>
                {
                    b.HasOne("App_Bancaria_Backend.Models.GrupoAhorro", "GrupoAhorro")
                        .WithMany("Aportes")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_Bancaria_Backend.Models.Transaccion", "Transaccion")
                        .WithMany("Aportes")
                        .HasForeignKey("IdTransaccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_Bancaria_Backend.Models.Usuario", "Usuario")
                        .WithMany("Aportes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoAhorro");

                    b.Navigation("Transaccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.Cuenta", b =>
                {
                    b.HasOne("App_Bancaria_Backend.Models.Usuario", "Usuario")
                        .WithOne("Cuenta")
                        .HasForeignKey("App_Bancaria_Backend.Models.Cuenta", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.GrupoAdministrador", b =>
                {
                    b.HasOne("App_Bancaria_Backend.Models.GrupoAhorro", "GrupoAhorro")
                        .WithMany("Administradores")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_Bancaria_Backend.Models.Usuario", "Usuario")
                        .WithMany("GruposAdmin")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoAhorro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.GrupoMiembro", b =>
                {
                    b.HasOne("App_Bancaria_Backend.Models.GrupoAhorro", "GrupoAhorro")
                        .WithMany("Miembros")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_Bancaria_Backend.Models.Usuario", "Usuario")
                        .WithMany("GruposMiembro")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoAhorro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.Retiro", b =>
                {
                    b.HasOne("App_Bancaria_Backend.Models.GrupoAhorro", "GrupoAhorro")
                        .WithMany("Retiros")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_Bancaria_Backend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuarioSolicitante")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("GrupoAhorro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.RetiroAprobacion", b =>
                {
                    b.HasOne("App_Bancaria_Backend.Models.Retiro", "Retiro")
                        .WithMany("Aprobaciones")
                        .HasForeignKey("IdRetiro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App_Bancaria_Backend.Models.Usuario", "Usuario")
                        .WithMany("Aprobaciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Retiro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.Transaccion", b =>
                {
                    b.HasOne("App_Bancaria_Backend.Models.Cuenta", "CuentaDestino")
                        .WithMany("TransaccionesDestino")
                        .HasForeignKey("IdCuentaDestino")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("App_Bancaria_Backend.Models.Cuenta", "CuentaOrigen")
                        .WithMany("TransaccionesOrigen")
                        .HasForeignKey("IdCuentaOrigen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App_Bancaria_Backend.Models.TipoTransaccion", "TipoTransaccion")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdTipoTransaccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuentaDestino");

                    b.Navigation("CuentaOrigen");

                    b.Navigation("TipoTransaccion");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.Cuenta", b =>
                {
                    b.Navigation("TransaccionesDestino");

                    b.Navigation("TransaccionesOrigen");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.GrupoAhorro", b =>
                {
                    b.Navigation("Administradores");

                    b.Navigation("Aportes");

                    b.Navigation("Miembros");

                    b.Navigation("Retiros");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.Retiro", b =>
                {
                    b.Navigation("Aprobaciones");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.TipoTransaccion", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.Transaccion", b =>
                {
                    b.Navigation("Aportes");
                });

            modelBuilder.Entity("App_Bancaria_Backend.Models.Usuario", b =>
                {
                    b.Navigation("Aportes");

                    b.Navigation("Aprobaciones");

                    b.Navigation("Cuenta")
                        .IsRequired();

                    b.Navigation("GruposAdmin");

                    b.Navigation("GruposMiembro");
                });
#pragma warning restore 612, 618
        }
    }
}
